import { $, el, emit, on, setStatus, state } from "./state.js";

const IN_TAURI = typeof window !== "undefined" && !!window.__TAURI__;

async function invoke(cmd, args) {
  return window.__TAURI__.core.invoke(cmd, args);
}

function ensureScreen(name) {
  if (!state.ui.screens[name]) {
    state.ui.screens[name] = { windows: {}, custom: [] };
    state.ui.order.push(name);
  }
  return state.ui.screens[name];
}

export function importTreeData(j) {
  const scr = j.screen || "world_select";
  const s = ensureScreen(scr);
  s.windows = {};
  (j.widgets || []).forEach((w, i) => {
    const id = w.path || w.id;
    s.windows[id] = {
      x: w.x ?? 80 + (i % 4) * 230,
      y: w.y ?? 90 + Math.floor(i / 4) * 120,
      w: w.w || 150,
      h: w.h || 30,
      visible: w.visible !== false,
    };
  });
  state.ui.active = scr;
  state.ui.sel = null;
  emit("ui-tree");
}

export function renderUiStage() {
  const stage = $("#uiStage");
  if (!stage) return;
  stage.replaceChildren();
  const bg = el("img", {
    class: "game-bg",
    src: "textures/ch_select_bg.png",
    alt: "",
  });
  stage.append(bg);

  const scr = state.ui.screens[state.ui.active];
  if (!scr) return;
  for (const [id, w] of Object.entries(scr.windows)) {
    if (w.x === undefined && w.y === undefined && !w.w) continue;
    const d = el("div", {
      class: "nw" + (state.ui.sel === id ? " selected" : ""),
    });
    d.style.left = (w.x ?? 0) + "px";
    d.style.top = (w.y ?? 0) + "px";
    d.style.width = (w.w || 100) + "px";
    d.style.height = (w.h || 40) + "px";
    d.append(el("div", { class: "nw-label", text: id }));
    d.onclick = (ev) => {
      ev.stopPropagation();
      state.ui.sel = id;
      emit("ui-tree");
    };
    d.onmousedown = (ev) => {
      if (ev.button !== 0) return;
      ev.preventDefault();
      ev.stopPropagation();
      state.ui.sel = id;
      emit("ui-tree");
      const sx = ev.clientX;
      const sy = ev.clientY;
      const ox = w.x || 0;
      const oy = w.y || 0;
      const mv = (e2) => {
        w.x = Math.round(ox + (e2.clientX - sx));
        w.y = Math.round(oy + (e2.clientY - sy));
        d.style.left = w.x + "px";
        d.style.top = w.y + "px";
      };
      const up = () => {
        document.removeEventListener("mousemove", mv);
        document.removeEventListener("mouseup", up);
        emit("ui-tree");
      };
      document.addEventListener("mousemove", mv);
      document.addEventListener("mouseup", up);
    };
    stage.append(d);
  }
}

export function renderUiInspector(root) {
  const exportBtn = el("button", {
    class: "act primary",
    text: "Export overrides.lua",
  });
  exportBtn.onclick = doExport;

  if (!state.ui.sel || !state.ui.active) {
    root.append(
      el("div", { class: "h3", text: "UI widget" }),
      el("p", { class: "kv", text: "Select a native window in the tree or canvas." }),
      exportBtn,
    );
    return;
  }
  const s = state.ui.screens[state.ui.active];
  const w = s?.windows[state.ui.sel];
  if (!w) {
    root.append(el("div", { class: "h3", text: "Unknown" }), exportBtn);
    return;
  }
  root.append(el("div", { class: "h3", text: "Native window" }));
  root.append(el("p", { class: "kv", text: "ID: " + state.ui.sel }));
  const xid = el("input", { type: "number", id: "ni_x", value: w.x || 0 });
  const yid = el("input", { type: "number", id: "ni_y", value: w.y || 0 });
  const wid = el("input", { type: "number", id: "ni_w", value: w.w || 200 });
  const hid = el("input", { type: "number", id: "ni_h", value: w.h || 50 });
  root.append(el("label", { text: "X" }), xid);
  root.append(el("label", { text: "Y" }), yid);
  root.append(el("label", { text: "Width" }), wid);
  root.append(el("label", { text: "Height" }), hid);
  const apply = el("button", { class: "act", text: "Apply" });
  apply.onclick = () => {
    w.x = +xid.value;
    w.y = +yid.value;
    w.w = +wid.value;
    w.h = +hid.value;
    emit("ui-tree");
  };
  root.append(apply, exportBtn);
}

function genLua() {
  const q = (v) =>
    '"' +
    String(v ?? "")
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"') +
    '"';
  const out = [
    "-- overrides.lua — generated by ArcheaAge Editor",
    "",
    "IVAN_OVERRIDES = {",
  ];
  for (const scrName of state.ui.order) {
    for (const [id, w] of Object.entries(state.ui.screens[scrName].windows)) {
      out.push(
        `    { id = "${id}", action = "apply", show = true, ` +
          `anchor = { "TOPLEFT", "UIParent", ${w.x || 0}, ${w.y || 0} }, ` +
          `extent = { ${w.w || 200}, ${w.h || 50} } },`,
      );
    }
  }
  out.push("}");
  out.push("", "IVAN_CUSTOM = {");
  for (const scrName of state.ui.order) {
    for (const c of state.ui.screens[scrName].custom || []) {
      const col = c.color ? ` color = "${c.color}",` : "";
      out.push(
        `    { id = "${c.id}", anchor = { "TOPLEFT", "UIParent", ${c.x}, ${c.y} }, ` +
          `extent = { ${c.w || 200}, ${c.h || 40} }, text = ${q(c.text)},${col} show = true },`,
      );
    }
  }
  out.push("}");
  return out.join("\n");
}

export async function doExport() {
  const lua = genLua();
  if (IN_TAURI) {
    try {
      const p = await invoke("overrides_save", { content: lua });
      setStatus("saved: " + p);
    } catch (e) {
      setStatus(String(e));
    }
  } else {
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([lua], { type: "text/plain" }));
    a.download = "overrides.lua";
    a.click();
    setStatus("downloaded overrides.lua");
  }
}

export function bindUiMode() {
  on("ui-tree", () => {
    renderUiStage();
  });
  on("ui-select-screen", (name) => {
    state.ui.active = name;
    state.ui.sel = null;
    emit("ui-tree");
  });
  on("ui-select-widget", ({ screen, id }) => {
    state.ui.active = screen;
    state.ui.sel = id;
    emit("ui-tree");
  });
  on("ui-inspector", (root) => renderUiInspector(root));
  on("cmd", (cmd) => {
    if (cmd === "ui-export") doExport();
  });

  fetch("game_ui_tree.json")
    .then((r) => (r.ok ? r.json() : Promise.reject()))
    .then(importTreeData)
    .catch(() => {});
}
