-- addon_panel.lua — "ivanpanel": info panel on the world/server-select screen.
-- Hooked ONLY from loginstage/world_select/toc.g (one module = one instance).
-- Diagnostics live in probe_dump.lua (separate chunk).

local win = CreateEmptyWindow("ivanPanelWin", "UIParent")
win:Show(true)
win:SetExtent(260, 110)
win:AddAnchor("TOPRIGHT", "UIParent", -18, 84)

local function lbl(id, text, dy, r, g, b)
    local l = win:CreateChildWidget("label", id, 0, true)
    l:SetAutoResize(true)
    l:SetText(text)
    pcall(function() l.style:SetShadow(true) end)
    l.style:SetColor(r, g, b, 1)
    l:AddAnchor("TOPRIGHT", win, -10, dy)
    return l
end

lbl("ipTitle", "ArcheaAge", 6, 0.85, 0.78, 0.45)
lbl("ipBy",   "Edited by Ivan Cavero", 34, 0.92, 0.92, 0.96)

local function firstNumber(fns)
    for _, f in ipairs(fns) do
        local ok, v = pcall(f)
        if ok and type(v) == "number" then return v end
    end
    return nil
end

-- real data: these are the same globals world_select's own code uses
local remain = firstNumber({ GetRemainCreatableCharacterCount })
local total  = firstNumber({ GetWorldCharacterCount })
if total then
    lbl("ipChars", ("Personajes: %d creados"):format(total), 60, 0.62, 0.72, 0.85)
elseif remain then
    lbl("ipChars", ("Puedes crear %d más"):format(remain), 60, 0.62, 0.72, 0.85)
else
    lbl("ipServer", "Servidor \194\183 EU-1", 60, 0.62, 0.72, 0.85)
end

lbl("ipBuild", "Build custom \194\183 preview UI", 82, 0.55, 0.65, 0.80)

-- ------------------------------------------------------------- overrides --
-- Declarative edits generated by the visual editor (tools/ui/editor).
-- push-ui.ps1 prepends overrides.lua (defining IVAN_OVERRIDES) to this chunk.
-- Widget LOOKUP needs accessor names confirmed by probe_dump.lua output.
local OVERRIDES = IVAN_OVERRIDES or {}

local function findWidget(id)
    local attempts = {
        function() return UIParent:GetChild(id) end,
        function() return UIParent:GetWidget(id) end,
        function() return _G[id] end,
    }
    for _, f in ipairs(attempts) do
        local ok, v = pcall(f)
        if ok and v ~= nil then return v end
    end
    return nil
end

for _, o in ipairs(OVERRIDES) do
    local w = findWidget(o.id or "")
    if w == nil then
        -- widget not found: silently skipped until lookup is wired
    elseif o.action == "hide" then
        pcall(function() w:Show(false) end)
    else
        pcall(function()
            local a = o.anchor or { "TOPLEFT", "UIParent", 0, 0 }
            w:AddAnchor(a[1], a[2], a[3], a[4])
            if o.text then w:SetText(o.text) end
            if o.color then w.style:SetColor(o.color[1], o.color[2], o.color[3], o.color[4] or 1) end
        end)
    end
end
