-- addon_panel.lua — "ivanpanel": info panel on the world/server-select screen.
-- Hooked ONLY from loginstage/world_select/toc.g (one module = one instance).

-- ---------------------------------------------------------------- explorer --
-- Dump every global + probe widget-tree accessors, so tooling can learn the
-- real API surface without guessing. Written next to bin32 (cwd of the game).
local LOG = nil
pcall(function() LOG = io.open("../ivanpanel_env.txt", "w") end)
local function L(s)
    if LOG then LOG:write(tostring(s) .. "\n") LOG:flush() end
end

L("=== globals (" .. tostring(_G ~= nil) .. ") ===")
pcall(function()
    local names = {}
    for k, v in pairs(_G) do names[#names + 1] = tostring(k) .. "\t" .. type(v) end
    table.sort(names)
    for _, n in ipairs(names) do L(n) end
end)

L("=== method probes ===")
local function probe(obj, name)
    if obj == nil then L(name .. ": <nil obj>") return end
    local t = type(obj)
    L(name .. " <" .. t .. ">")
    if t ~= "table" and t ~= "userdata" then return end
    for _, m in ipairs({ "GetNumChildren", "GetChild", "GetChildren", "GetId",
                         "GetName", "GetExtent", "GetWidth", "GetHeight",
                         "GetAnchor", "IsVisible", "GetUILayer" }) do
        local v = obj[m]
        if v ~= nil then L("  has " .. m .. " <" .. type(v) .. ">") end
    end
end

probe(UIParent, "UIParent")
probe(X2LoginCharacter, "X2LoginCharacter")
probe(X2Unit, "X2Unit")
probe(X2World, "X2World")
probe(X2, "X2")

if LOG then LOG:close() LOG = nil end
-- -------------------------------------------------------------- /explorer --

local win = CreateEmptyWindow("ivanPanelWin", "UIParent")
win:Show(true)
win:SetExtent(260, 110)
win:AddAnchor("TOPRIGHT", "UIParent", -18, 84)

local function lbl(id, text, dy, r, g, b)
    local l = win:CreateChildWidget("label", id, 0, true)
    l:SetAutoResize(true)
    l:SetText(text)
    pcall(function() l.style:SetShadow(true) end)
    l.style:SetColor(r, g, b, 1)
    l:AddAnchor("TOPRIGHT", win, -10, dy)
    return l
end

lbl("ipTitle", "ArcheaAge", 6, 0.85, 0.78, 0.45)
lbl("ipBy",   "Edited by Ivan Cavero", 34, 0.92, 0.92, 0.96)

-- character count: only shown when the API actually returns numbers here
local function firstNumber(fns)
    for _, f in ipairs(fns) do
        local ok, v = pcall(f)
        if ok and type(v) == "number" then return v end
    end
    return nil
end

local total = firstNumber({
    function() return X2LoginCharacter:GetCurrentTotalCharactersCount() end,
    function() return X2LoginCharacter:GetTotalCharactersCount() end,
})
local limit = firstNumber({
    function() return X2LoginCharacter:GetCurrentTotalCharactersLimit() end,
})
if total and limit then
    lbl("ipChars", ("Personajes: %d / %d"):format(total, limit), 60, 0.62, 0.72, 0.85)
else
    lbl("ipServer", "Servidor \194\183 EU-1", 60, 0.62, 0.72, 0.85)
end

lbl("ipBuild", "Build custom \194\183 preview UI", 82, 0.55, 0.65, 0.80)

-- ------------------------------------------------------------- overrides --
-- Phase 2: declarative edits generated by the visual editor (tools/ui/editor).
-- push-ui.ps1 prepends overrides.lua (defining IVAN_OVERRIDES) to this chunk.
-- Widget LOOKUP needs the real accessor names from ivanpanel_env.txt; until
-- then every candidate is tried under pcall and misses are logged+skipped.
local OVERRIDES = IVAN_OVERRIDES or {}

local function findWidget(id)
    local attempts = {
        function() return UIParent:GetChild(id) end,
        function() return UIParent:GetWidget(id) end,
        function() return _G[id] end,
    }
    for _, f in ipairs(attempts) do
        local ok, v = pcall(f)
        if ok and v ~= nil then return v end
    end
    return nil
end

for _, o in ipairs(OVERRIDES) do
    local w = findWidget(o.id or "")
    if w == nil then
        L("override: widget no encontrado: " .. tostring(o.id))
    elseif o.action == "hide" then
        pcall(function() w:Show(false) end)
    else
        pcall(function()
            local a = o.anchor or { "TOPLEFT", "UIParent", 0, 0 }
            w:AddAnchor(a[1], a[2], a[3], a[4])
            if o.text then w:SetText(o.text) end
            if o.color then w.style:SetColor(o.color[1], o.color[2], o.color[3], o.color[4] or 1) end
        end)
    end
end
