-- addon_panel.lua — ArcheaAge UI addon: info panel on the world/server-select screen.
-- Hooked ONLY from loginstage/world_select/toc.g.
--
-- CONFIG: reads <USERPROFILE>/Documents/ArcheAge/aa_ui_config.lua at load
-- (plain text, editable with notepad). Missing file -> built-in defaults.

-- ---- config loading -------------------------------------------------------
local CFG = {
    title     = "ArcheaAge",
    byline    = "ArcheaAge",
    server    = "Servidor \194\183 EU-1",
    build     = "Build custom \194\183 preview UI",
    offset_x  = -18,
    offset_y  = 70,
    color_title = { 0.85, 0.78, 0.45 },
    color_text  = { 0.62, 0.72, 0.85 },
}
pcall(function()
    local home = os.getenv and os.getenv("USERPROFILE") or ""
    local f = io.open(home .. "/Documents/ArcheAge/aa_ui_config.lua", "r")
    if f then
        local body = f:read("*a") f:close()
        local fn = loadstring(body)
        if fn then
            local ok, userCfg = pcall(fn)
            if ok and type(userCfg) == "table" then
                for k, v in pairs(userCfg) do CFG[k] = v end
            end
        end
    end
end)

local function rgb(c) return c[1], c[2], c[3], c[4] or 1 end

-- ---- panel -----------------------------------------------------------------
local win = CreateEmptyWindow("aaUiWin", "UIParent")
win:Show(true)
win:SetExtent(280, 158)
win:AddAnchor("TOPRIGHT", "UIParent", CFG.offset_x, CFG.offset_y)

local function lbl(id, text, dy, color)
    local l = win:CreateChildWidget("label", id, 0, true)
    l:SetAutoResize(true)
    l:SetText(text)
    pcall(function() l.style:SetShadow(true) end)
    l.style:SetColor(rgb(color))
    l:AddAnchor("TOPRIGHT", win, -12, dy)
    return l
end

lbl("ipTitle", CFG.title,      6,   CFG.color_title)
lbl("ipBy",    CFG.byline,     34,  { 0.92, 0.92, 0.96 })
lbl("ipServer",CFG.server,     58,  CFG.color_text)

-- reserved slot: character count when the server sends it
local chars = lbl("ipChars", "", 82, CFG.color_text)

local live = lbl("ipLive",  "",             106, { 0.60, 0.78, 0.60 })
lbl("ipBuild", CFG.build,      130, { 0.55, 0.65, 0.80 })

-- ------------------------------------------------------------ live refresh --
local frames, tries = 0, 0
pcall(function()
    win:SetHandler("OnUpdate", function()
        frames = frames + 1
        if frames % 30 ~= 0 then return end            -- ~1 Hz

        local fps = nil
        pcall(function() fps = UIParent:GetFrameRate() end)
        local ok, hms = pcall(function() return os.date("%H:%M:%S") end)
        pcall(function()
            live:SetText(("FPS %d \194\183 %s"):format(fps or 0, ok and hms or ""))
        end)

        tries = tries + 1
        if tries <= 15 then                            -- char count grace window
            local okc, n = pcall(GetWorldCharacterCount)
            if okc and type(n) == "number" then
                pcall(function() chars:SetText(("Personajes: %d"):format(n)) end)
                tries = 999
            end
        end
    end)
end)

-- ------------------------------------------------------------- overrides --
-- Declarative edits (tools/ui/overrides.lua or generated by UI Studio).
-- push-ui.ps1 prepends that file, which assigns IVAN_OVERRIDES.
-- DEFERRED application with retries: several native windows are created after
-- module load and ship hidden — entries can set show=true to reveal them.
local OVERRIDES = IVAN_OVERRIDES or {}

local OVLOG = io.open(home .. "/Documents/ArcheAge/aa_ui_ovr.txt", "w")
local function OL(s) if OVLOG then OVLOG:write(tostring(s) .. "\n"); OVLOG:flush() end end

local function rgbArr(c)
    if type(c) ~= "table" then return nil end
    return c[1], c[2], c[3], c[4] or 1
end

local function resolvePath(path)
    local obj = _G
    for part in string.gmatch(path, "[^%.]+") do
        local base, idx = part:match("^(.-)%[(%d+)%]$")
        if base and idx then
            obj = obj[base]
            if type(obj) ~= "table" then return nil end
            obj = obj[tonumber(idx)]
        else
            obj = obj[part]
        end
        if obj == nil then return nil end
    end
    return obj
end

local function tryApply(o)
    local id = o.id or ""
    local w = resolvePath(id)
    if type(w) ~= "table" then
        OL("pendiente (no existe aun): " .. id)
        return false
    end
    local okAll = true
    pcall(function()
        if o.action == "hide" then w:Show(false) end
        if o.show then w:Show(true) end
        if o.anchor then
            pcall(function() w:RemoveAllAnchors() end)
            w:AddAnchor(o.anchor[1], o.anchor[2], o.anchor[3], o.anchor[4])
        end
        if o.text then w:SetText(o.text) end
        if o.color then w.style:SetColor(rgbArr(o.color)) end
    end)
    OL("aplicado: " .. id .. " (" .. tostring(o.action or "apply") .. ")")
    return okAll
end

-- pass 1: whatever resolves right now
local pending = {}
for _, o in ipairs(OVERRIDES) do o._done = tryApply(o); if not o._done then pending[#pending+1] = o end end

-- pass 2: deferred retries until all land (or give up after ~10 s)
if #pending > 0 then
    local oframes, otries = 0, 0
    pcall(function()
        win:SetHandler("OnUpdate", function()
            oframes = oframes + 1
            if oframes % 30 ~= 0 then return end
            otries = otries + 1
            local left = 0
            for _, o in ipairs(pending) do
                if not o._done then
                    o._done = tryApply(o)
                    if not o._done then left = left + 1 end
                end
            end
            OL("reintento " .. otries .. " · quedan=" .. left)
            if left == 0 or otries >= 20 then
                OL("overrides fin (quedan=" .. left .. ", intentos=" .. otries .. ")")
                pcall(function() win:ReleaseHandler("OnUpdate") end)
                if OVLOG then OVLOG:close() OVLOG = nil end
            end
        end)
    end)
elseif OVLOG then
    OVLOG:close() OVLOG = nil
end

-- -------------------------------------------------------- custom widgets --
-- Widgets designed in UI Studio (IVAN_CUSTOM) — created by this addon at load.
-- Each entry: { id, type="label"|"window", anchor={pt,rel,x,y},
--               extent={w,h}, text=?, color={r,g,b}, show=? }
local CUSTOM = IVAN_CUSTOM or {}
for _, c in ipairs(CUSTOM) do
    pcall(function()
        if c.show == false then return end
        local w = CreateEmptyWindow(c.id, "UIParent")
        w:Show(true)
        local ext = c.extent or { 180, 26 }
        w:SetExtent(ext[1], ext[2])
        local a = c.anchor or { "TOPLEFT", "UIParent", 0, 0 }
        w:AddAnchor(a[1], a[2], a[3], a[4])
        if c.type ~= "window" and c.text then
            local l = w:CreateChildWidget("label", c.id .. "_lbl", 0, true)
            l:SetAutoResize(true)
            l:SetText(c.text)
            pcall(function() l.style:SetShadow(true) end)
            if c.color then l.style:SetColor(rgbArr(c.color)) end
            l:AddAnchor("CENTER", w, 0, 0)
        end
    end)
end
